package br.unibh.sdm.entidades;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "usuario")
public class Usuario {

	private String idUsuario;
	private String emailUsuario;
	private String senhaUsuario;
	private String nomeUsuario;
	

	public Usuario() {
		super();
	}

	public Usuario(String idUsuario, String emailUsuario, String senhaUsuario, String nomeUsuario) {
		super();
		this.idUsuario = idUsuario;
		this.emailUsuario = emailUsuario;
		this.senhaUsuario = senhaUsuario;
		this.nomeUsuario = nomeUsuario;
	}

	@DynamoDBHashKey
	@DynamoDBAutoGeneratedKey
	public String getIdUsuario() {
		return idUsuario;
	}

	public void setIdUsuario(String idUsuario) {
		this.idUsuario = idUsuario;
	}
	@DynamoDBAttribute
	public String getEmailUsuario() {
		return emailUsuario;
	}
	
	public void setEmailUsuario(String emailUsuario) {
		this.emailUsuario = emailUsuario;
	}
	@DynamoDBAttribute
	public String getSenhaUsuario() {
		return senhaUsuario;
	}

	public void setSenhaUsuario(String senhaUsuario) {
		this.senhaUsuario = senhaUsuario;
	}
	@DynamoDBAttribute
	public String getNomeUsuario() {
		return nomeUsuario;
	}

	public void setNomeUsuario(String nomeUsuario) {
		this.nomeUsuario = nomeUsuario;
	}

	@Override
	public String toString() {
		return "Usuario [idUsuario=" + idUsuario + ", emailUsuario=" + emailUsuario + ", senhaUsuario=" + senhaUsuario
				+ ", nomeUsuario=" + nomeUsuario + "]";
	}

	
}
